import { $fetch } from 'ofetch';
import type { Hex } from 'viem';
import { type SoDEXNetwork, NETWORK_CONFIG } from './types.js';
import {
  type ActionPayload,
  type SoDEXSigner,
  type SigningDomain,
  actionJson,
} from './signing.js';

type JsonFetchOptions = Parameters<typeof $fetch>[1];

export class SoDEXAPIError extends Error {
  override name: string = 'SoDEXAPIError';
  readonly statusCode: number;
  readonly responseCode: number | undefined;

  constructor(message: string, statusCode: number, responseCode?: number) {
    super(message);
    this.statusCode = statusCode;
    if (responseCode !== undefined) this.responseCode = responseCode;
  }
}

export interface SoDEXClientConfig {
  network: SoDEXNetwork;
  signer?: SoDEXSigner;
  /** Optional API key NAME (an EVM address generated by SoDEX), sent in X-API-Key. */
  apiKeyName?: string;
  /** Override base URL (no /api/v1 suffix, e.g. "https://testnet-gw.sodex.dev"). */
  baseUrl?: string;
  timeout?: number;
  maxRetries?: number;
}

const SPOT_BASE = '/api/v1/spot';
const PERPS_BASE = '/api/v1/perps';

/**
 * Low-level HTTP client. Mirrors the official Go SDK's request shape exactly:
 *  - GETs are unauthenticated (market data + public account queries).
 *  - POSTs/DELETEs carry the JSON action body and EIP-712 signature in HEADERS:
 *    X-API-Sign, X-API-Nonce, X-API-Chain, optionally X-API-Key.
 */
export class SoDEXClient {
  readonly network: SoDEXNetwork;
  readonly chainId: number;
  readonly baseUrl: string;
  private readonly signer?: SoDEXSigner;
  private readonly apiKeyName?: string;
  private readonly timeout: number;
  private readonly maxRetries: number;

  constructor(config: SoDEXClientConfig) {
    const cfg = NETWORK_CONFIG[config.network];
    this.network = config.network;
    this.chainId = cfg.chainId;
    // Strip any /api/v1/spot or /api/v1/perps suffix — paths are full from /api/...
    this.baseUrl =
      config.baseUrl ?? cfg.spotBaseUrl.replace(/\/api\/v1\/(spot|perps)\/?$/, '');
    if (config.signer !== undefined) this.signer = config.signer;
    if (config.apiKeyName !== undefined) this.apiKeyName = config.apiKeyName;
    this.timeout = config.timeout ?? 30_000;
    this.maxRetries = config.maxRetries ?? 2;
  }

  get spotBase() {
    return SPOT_BASE;
  }
  get perpsBase() {
    return PERPS_BASE;
  }

  /** Public GET — unauthenticated. */
  async get<T = unknown>(path: string, query?: Record<string, unknown>): Promise<T> {
    const opts: JsonFetchOptions = {
      method: 'GET',
      baseURL: this.baseUrl,
      timeout: this.timeout,
      retry: this.maxRetries,
      retryDelay: 250,
      retryStatusCodes: [408, 429, 500, 502, 503, 504],
    };
    if (query !== undefined) opts.query = this.cleanQuery(query);
    try {
      return (await $fetch(path, opts)) as T;
    } catch (err: unknown) {
      throw this.toApiError(err, path);
    }
  }

  /** Authenticated POST — signs the body and attaches X-API-* headers. */
  async postSigned<T = unknown>(
    domain: SigningDomain,
    path: string,
    payload: ActionPayload,
  ): Promise<T> {
    return this.signedRequest('POST', domain, path, payload);
  }

  /** Authenticated DELETE — same envelope as POST, used for cancel orders. */
  async deleteSigned<T = unknown>(
    domain: SigningDomain,
    path: string,
    payload: ActionPayload,
  ): Promise<T> {
    return this.signedRequest('DELETE', domain, path, payload);
  }

  private async signedRequest<T>(
    method: 'POST' | 'DELETE',
    domain: SigningDomain,
    path: string,
    payload: ActionPayload,
  ): Promise<T> {
    if (!this.signer) {
      throw new Error('SoDEXClient: signer is required for write actions');
    }
    const signed = await this.signer.sign(payload, domain);
    // Body is the unwrapped params (the server reads /params/, not the type wrapper —
    // the type wrapper is only used to compute payloadHash). The server reads the
    // action type from the URL path.
    const body = actionJson(payload.params);

    const headers: Record<string, string> = {
      'content-type': 'application/json',
      accept: 'application/json',
      'X-API-Sign': signed.signature,
      'X-API-Nonce': signed.nonce.toString(),
      'X-API-Chain': this.chainId.toString(),
    };
    if (this.apiKeyName) headers['X-API-Key'] = this.apiKeyName;

    try {
      return (await $fetch(path, {
        method,
        baseURL: this.baseUrl,
        timeout: this.timeout,
        body,
        headers,
      })) as T;
    } catch (err: unknown) {
      throw this.toApiError(err, path);
    }
  }

  get signerAddress(): Hex {
    if (!this.signer) throw new Error('SoDEXClient: no signer configured');
    return this.signer.address;
  }

  private cleanQuery(query: Record<string, unknown>): Record<string, string> {
    const out: Record<string, string> = {};
    for (const [k, v] of Object.entries(query)) {
      if (v !== undefined && v !== null) out[k] = String(v);
    }
    return out;
  }

  private toApiError(err: unknown, path: string): Error {
    type FetchError = {
      statusCode?: number;
      data?: { message?: string; code?: number };
      message?: string;
    };
    const e = err as FetchError;
    const status = e.statusCode ?? 0;
    const message = e.data?.message ?? e.message ?? 'Unknown error';
    return new SoDEXAPIError(
      `SoDEX API error on ${path} (${status}): ${message}`,
      status,
      e.data?.code,
    );
  }
}
